apiVersion: automation.cloudbees.io/v1alpha1
kind: action
name: "CDRO Actions"
inputs:
  url:
    description: 'CDRO URL'
    required: false
    default: 'https://sda.preview.cb-demos.io'
  username:
    description: 'CDRO Username'
    required: true
  user-token:
    description: 'CDRO User token'
    required: true
  project-name:
    description: 'project name'
    required: true
  release-name:
    description: 'release name'
    required: true


runs:
  using: composite
  steps:
    - id: invoke-cdro-action
      name: invoke-cdro-action
      uses: docker://fedora:39
      shell: sh
      run: |
        PROJECT=${{inputs.project-name }}
        RELEASE=${{inputs.release-name }}
        curl -k -X POST "${{ inputs.url }}/rest/v1.0/releases?projectName=${PROJECT}&releaseName=${RELEASE}" \
          -u ${{ inputs.username }}:${{ inputs.user-token }}
